name: Linux_Container_Workflow

on:
  push:
    branches:
      - master
      - stage
      - develop
  pull_request:
    branches:
      - master
      - stage
      - develop

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: Development
        steps:
        
        - name: get repository name
          run: echo "BUILD_REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
          shell: bash
        
        - name: Extract branch name (non-production)
          if: ${{ github.ref != 'refs/heads/main' }}
          shell: bash
          run: echo "BUILD_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

        - name: Extract branch name (production)
          if: ${{ github.ref == 'refs/heads/main' }}
          shell: bash
          run: echo "BUILD_BRANCH_NAME=$(echo 'production')" >> $GITHUB_ENV
        
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t goodyear.azurecr.io/${{ env.BUILD_REPOSITORY_NAME }}/deployreact:${{ github.sha }} --build-arg DEPLOY_ENVIRONMENT=${{ env.BUILD_BRANCH_NAME }}
            docker push goodyear.azurecr.io/${{ env.BUILD_REPOSITORY_NAME }}/deployreact:${{ github.sha }}

        - uses: azure/aks-set-context@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
            resource-group: 'aks-${{ env.BUILD_BRANCH_NAME }}'
            cluster-name: 'aks-${{ env.BUILD_BRANCH_NAME }}-001'
          id: login
          
        - uses: azure/k8s-deploy@v1.4
          with:
            namespace: ${{ secrets.GDY_PROJECT_NAMESPACE }}
            manifests: |
              manifests/deployment.yml
            images: |
              goodyear.azurecr.io/${{ env.BUILD_REPOSITORY_NAME }}/deployreact:${{ github.sha }}
